### ISSUE TITLE
Documentation I am working on...

### ISSUE THREAD

**Issue by elrayle** [elrayle/unix_utils#2]
- [ ] A to Z (Issue https://github.com/samvera/samvera.github.io/issues/85)
- [ ] Best Practices (Issue https://github.com/samvera/samvera.github.io/issues/61)
       * Use of Modules
       * Documenting Code, Tutorials, What happens when, etc.
- [ ] Design Patterns (Issue https://github.com/samvera/samvera.github.io/issues/75)
- [ ] Stack Overflow integration (Issue https://github.com/samvera/samvera.github.io/issues/62)
